### ISSUE TITLE
notes: re session 2 (SS24)

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-course-uhh-ss24#11]
- [ ] One person completed survey without codeword (30 Minutes before session)
- [x] IDEA: Ask them to define learning objectives of last sessions
- [x] Clarify: "Take The Quiz" does not mean they have to do it -  We announce every exercise they have to do
- [ ] Clarify: We use GitBASH for windows not GitGUI etc...
- [ ] IDEA: Add Working Copy to GUI chapter
- [x] Clarify: Using Rm == Very Dangerous
- [x] Clarify: You need to enable copy-paste in GitBash
- [ ] Clarify: This is just an intro you don't need to be able to do all that stuff on CLI for Git
- [ ] Clarify: Copy-Pasting Path on Windows -> Needs to be put in quotes
- [ ] Errror: https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a
- [ ] what does `.` and `..` indicate when I run the `ls -a` command
- [ ] how to list *only* hidden files?
- [ ] interference from other programming languages that one should worry about when using the command line? e.g., `clear all` that is often used in MATLAB
- [x] Clarify: Recipe ordner muss wieder gefunden werden
- [ ] ADD: on website: what they "should have" 
- [ ] IDEA: How to save command line history?

**Comment by lnnrtwttkhn** [comment]
some of these tasks were completed in #12

**Comment by konradpa** [comment]
This is all added/summarized in [here](https://github.com/lnnrtwttkhn/version-control-book/issues/241) by now
