### ISSUE TITLE
notes re: session05 (SS24)

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-course-uhh-ss24#19]
- [ ] Question: how to "change title of file" -> just open file regularly 
- [ ] Confusion of `echo "bla" >> file.txt` and `--amend` workflow
- [ ] how can I exit the git log view in one window: use `q` (this might apply to both macOS and Windows) 
- [ ] add background info why to use present tense in commit messages
- [ ]  Question: How to rename files in and rename git repository?
- [ ] Merge conflict: Commit on main branch essential before switch to feature branch and doing commit for merge conflict
- [ ] Merge Conflict: COMMITS need to differ for one to appear
- [ ] Question:  what happens if I delete main branch?
- [ ] Question: What happens to feature branch content after resolving merge conflict?
- [ ] FORMR: Bug first Mc question -> wrong feedback

**Comment by lnnrtwttkhn** [comment]
- [ ] add code to rename branch `git branch -m master main`
- [ ] if I enter the name of a folder, e.g., "meat" to .gitignore, does it also ignore subfolder? short answer: no
- [ ] problem with git config options resetting
- [ ] what do I do after I created a `.gitignore`
- [ ] which file extension does `.gitignore` have?

**Comment by konradpa** [comment]
This is all added/summarized in [here](https://github.com/lnnrtwttkhn/version-control-book/issues/241) by now
