### ISSUE TITLE
notes: re session 09

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-course-uhh-ss24#25]
- [x] Make clearer that you have to create git repo without README file
- [ ] GitHub password doesn't show up in command line, but you can still enter the password (yes, you can also copy and paste and delete)
- [x] book: bigger warning: don't init a github repo with files (maybe add explanation, why, i.e., because the initial commit diverges)
- [x] how to edit the remote url: either `git remote rm` and then redo or `git remote set-url`
- [ ] Git for Windows command line is buggy
- [ ] Show SSH as alternative
- [x] If asked for password to connect to GitHub from CLI, use PAT not GitHub account password
- [x] Windows open up a new window for PAT, in macOS you can often use the CLI
- [ ] for course: add commands to remove a .git repo / folder from the user directory
- [ ] emphasize to not forget to delete branches!
- [ ] book: add commands that visualize branches better

questions by students:

- [ ] how do I delete files directly in Github and are they automatically deleted from my local repository when I make a pull request?
- [ ] what are unnecessary files that we can delete (task 2)? For example empty-file.docx and empty folder with .gitkeep?
- [ ] not all files are visible in the list in Github that I can see locally in the repository on my PC in Explorer, so I am wondering about the cause: Is it correct that all the files contained in .gitignore are not visible, or is it because only the files for which there were commits are listed in Github?

Translated with DeepL.com (free version)

general questions:

- [ ] how to use GUIs (especially RStudio)
- [ ] scientific use-cases for Git (show examples)

**Comment by lnnrtwttkhn** [comment]
>  how do I delete files directly in Github and are they automatically deleted from my local repository when I make a pull request?

- yes, you can delete a file directory in github
- click on the three buttons and select "delete directory"
- then commit changes
- this effectively runs git add and git commit on github

> what are unnecessary files that we can delete (task 2)? For example empty-file.docx and empty folder with .gitkeep?

- clean up the repository
- remove plain txt files, copy recipes to the quarto file
- keep .gitignore, README.md

>  not all files are visible in the list in Github that I can see locally in the repository on my PC in Explorer, so I am wondering about the cause: Is it correct that all the files contained in .gitignore are not visible, or is it because only the files for which there were commits are listed in Github?

- only files that you track with git are shown
- files or folder that you don't track or explicitly ignore, don't end up on github

**Comment by konradpa** [comment]
This is all added/summarized in [here](https://github.com/lnnrtwttkhn/version-control-book/issues/241) by now
