### ISSUE TITLE
notes: re session 10 (during/after)

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/version-control-course-uhh-ss24#31]
- [ ] lnnrtwttkhn/version-control-book#230
- [ ] Question: Issue number confusion

**Comment by lnnrtwttkhn** [comment]
> Question: Issue number confusion

Can you still say what this is about @konradpa?

**Comment by konradpa** [comment]
> > Question: Issue number confusion
> 
> Can you still say what this is about @konradpa?

I think the question was if an issue number is automatically created or If you have to create one

**Comment by konradpa** [comment]
This is all added/summarized in [here](https://github.com/lnnrtwttkhn/version-control-book/issues/241) by now
