### ISSUE TITLE
GUIs and other interfaces

### ISSUE THREAD

**Issue by paul-gallenkemper** [lnnrtwttkhn/version-control-course-uhh-ss24#34]
I'd like to learn a bit about differnt ways to call Git. 
I've noticed Git can be called via the R Studio Terminal, but there is also a Git Window for R Projects. 
Git can also be called in the Matlab Terminal - is there a similar build-in verison of Git in Matlab?

Then, what about GUIs? Which one has which benefits and what are payment options? Git kraken looked really promising, is it worth it?

**Comment by konradpa** [comment]
This is all added/summarized in [here](https://github.com/lnnrtwttkhn/version-control-book/issues/241) by now
